### ISSUE TITLE
catlab gets wrong TO value from web form

### ISSUE THREAD

**Issue by speleolinux** [spikelynch/Osiris#22]
I entered for the TO input field "test.pvl" but it seems to have this:
catlab APPEND= FROM=../1/V01062001.even.cub TO=test.pvl.txt *.prt *.pvl

**Comment by spikelynch** [comment]
Misunderstanding of the <filter> element in the XML: many programs can output more than one file type, and for eg catlab has <filter>*.txt *.prt *.pvl</filter>
http://www.youtube.com/watch?v=MKFSBN2mRhw
Now fixed:
- for parameters with multiple file types, the filter value is split, normalised for case and made into a drop-down menu next to the main filename
- for parameters with a single file type, form behaviour is the same as before (the extension is added to the user's filename)

Some output file parameters have no extension filter - for example, the output from isis2std - still need to check this.
